# Generated by Django 5.0.4 on 2026-05-17 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('brochure', 'Brochure'), ('lead_attachment', 'Lead Attachment'), ('dealer_document', 'Dealer Document'), ('invoice', 'Invoice'), ('warranty', 'Warranty'), ('other', 'Other')], default='other', max_length=40)),
                ('file_name', models.CharField(max_length=180)),
                ('file_url', models.URLField()),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigma_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='files_attac_content_28f0a4_idx'), models.Index(fields=['file_type', 'created_at'], name='files_attac_file_ty_83039b_idx')],
            },
        ),
    ]
