# Generated by Django 5.0.4 on 2026-05-17 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('business_type', models.CharField(choices=[('dealer', 'Dealer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('installer', 'Installer'), ('fleet_partner', 'Fleet Partner')], max_length=40)),
                ('region', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(db_index=True, max_length=80)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12)),
                ('gst_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('prospect', 'Prospect')], db_index=True, default='prospect', max_length=20)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='prospect', max_length=32)),
                ('monthly_performance', models.JSONField(blank=True, default=dict)),
                ('product_demand', models.JSONField(blank=True, default=dict)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active_leads_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dealers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('territory_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dealers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['state', 'city'], name='dealers_dea_state_2fc49c_idx'), models.Index(fields=['region', 'status'], name='dealers_dea_region_f2d569_idx'), models.Index(fields=['tier', 'status'], name='dealers_dea_tier_15a786_idx')],
            },
        ),
    ]
