# Generated by Django 5.0.4 on 2026-05-17 12:17

import apps.leads.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_id', models.CharField(db_index=True, default=apps.leads.models.generate_lead_id, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=140)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(db_index=True, max_length=80)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12)),
                ('lead_source', models.CharField(choices=[('website_form', 'Website Form'), ('whatsapp', 'WhatsApp'), ('dealer_inquiry', 'Dealer Inquiry'), ('distributor', 'Distributor'), ('direct_call', 'Direct Call'), ('manual_entry', 'Manual Entry'), ('social_media', 'Social Media')], db_index=True, max_length=40)),
                ('inquiry_type', models.CharField(choices=[('product', 'Product'), ('dealer', 'Dealer'), ('distributor', 'Distributor'), ('support', 'Support'), ('brochure', 'Brochure')], default='product', max_length=40)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conversion_probability', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('new', 'New'), ('attempted_contact', 'Attempted Contact'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('negotiation', 'Negotiation'), ('dealer_assigned', 'Dealer Assigned'), ('converted', 'Converted'), ('lost', 'Lost'), ('closed', 'Closed')], db_index=True, default='new', max_length=40)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='dealers.dealer')),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sigma_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('interested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigma_lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigma_lead_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority_level'], name='leads_lead_status_e7d8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['state', 'city'], name='leads_lead_state_014db0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_source', 'created_at'], name='leads_lead_lead_so_a34157_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_executive', 'status'], name='leads_lead_assigne_c5876c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_followup_at', 'status'], name='leads_lead_next_fo_e65dad_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtimelineevent',
            index=models.Index(fields=['lead', 'created_at'], name='leads_leadt_lead_id_8062c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtimelineevent',
            index=models.Index(fields=['action', 'created_at'], name='leads_leadt_action_9c7bed_idx'),
        ),
    ]
