# Generated by Django 5.0.4 on 2026-05-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('website_form', 'Website Form'), ('whatsapp_click', 'WhatsApp Click'), ('dealer_inquiry_click', 'Dealer Inquiry Click'), ('product_detail_request', 'Product Detail Request'), ('brochure_request', 'Brochure Request')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='integration_source_e7fe6d_idx'), models.Index(fields=['created_at', 'status'], name='integration_created_8cbec7_idx')],
            },
        ),
    ]
